# DB related constants:
SQL_TYPE = "mysql"
DB_PORT = 3306
DB_HOST = "localhost"
DB_USER = "root"
DB_PASSWORD = "1234"
DB_NAME = "test"
TABLE_NAME = "data"
COUNTER_NAME = "ID"
MAX_SIZE = 255
SALT = "WfLc6hyf"
MAX_ENTITY_ID_SIZE = 6

# Servers related constants:
LOAD_BALANCING_PORT = 15151
CLIENT_PORT = 26262

#Defaults
DEFAULT_HEALTH = 100
DEFAULT_INVENTORY = {}
DEFAULT_X = 900
DEFAULT_Y = 800
DEFAULT_STRENGTH = 0
DEFAULT_RESISTANCE = 0
DEFAULT_XP = 0
